# Generated by Django 3.0.5 on 2020-04-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_1', models.CharField(max_length=200)),
                ('col_2', models.TextField()),
                ('col_3', models.DateTimeField(verbose_name='date-published')),
                ('col_4', models.CharField(max_length=200)),
            ],
        ),
    ]
