# Generated by Django 3.0.5 on 2020-06-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0005_contact_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='username',
        ),
    ]
