# Generated by Django 3.0.5 on 2020-06-24 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startpage', '0009_auto_20200624_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentVehichle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(max_length=200)),
                ('vehichle_name', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=20)),
                ('whatsapp_no', models.IntegerField(max_length=20)),
                ('vehichle_no', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='media')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
