# Generated by Django 3.0.5 on 2020-06-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0010_rentvehichle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentvehichle',
            name='image',
            field=models.ImageField(default='', upload_to='vehichle images'),
        ),
    ]
