# Generated by Django 3.0.5 on 2020-06-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0011_auto_20200624_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentvehichle',
            name='vehichle_registration',
            field=models.FileField(default='', upload_to='vehichle registration'),
        ),
    ]
