# Generated by Django 3.0.5 on 2020-06-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0012_rentvehichle_vehichle_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentvehichle',
            old_name='image',
            new_name='vehichle_photo',
        ),
    ]
