# Generated by Django 3.0.5 on 2020-07-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0013_auto_20200625_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentvehichle',
            name='vehichle_no',
        ),
    ]
