# Generated by Django 3.0.5 on 2020-07-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0014_remove_rentvehichle_vehichle_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentvehichle',
            name='price',
        ),
        migrations.AddField(
            model_name='rentvehichle',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
