# Generated by Django 3.0.5 on 2020-07-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0015_auto_20200703_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentvehichle',
            old_name='vehichle_name',
            new_name='shop_name',
        ),
        migrations.RenameField(
            model_name='rentvehichle',
            old_name='vehichle_photo',
            new_name='shop_photo',
        ),
        migrations.RenameField(
            model_name='rentvehichle',
            old_name='vehichle_registration',
            new_name='shop_registration',
        ),
    ]
