# Generated by Django 2.2.3 on 2020-07-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0017_rentvehichle_hdstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentvehichle',
            name='whatsapp_no',
            field=models.IntegerField(default=0),
        ),
    ]
